### ISSUE TITLE
Feature Request: Drop-in replacement for `factory-girl` with support for `MongooseAdapter` and exported `factory` function.

### ISSUE THREAD

**Issue by titanism** [thiagomini/factory-girl-ts#34]
It would be great if this was a drop-in replacement for `factory-girl` with `MongooseAdapter` and `factory` as exports.

**Comment by thiagomini** [comment]
Hey @titanism , thanks for the feedback! Lately it has been quite busy on my side, but sure, I could work on that - in the meantime PRs are also more than welcome :)

**Comment by thiagomini** [comment]
Hey @titanism , sure, I'll set up GitHup Sponsors this weekend and we can further discuss this - I appreciate the enthusiasm :)
