### ISSUE TITLE
Overriding an associated key still creates a new instance in the database

### ISSUE THREAD

**Issue by dkpoult** [thiagomini/factory-girl-ts#35]
Hey there, firstly awesome revival of this package, it's made E2E testing our systems so much smoother than previous approached! But we've recently run into a bug/issue with creating instances:

In the `create` method of the Factory class, the method first gets the default attributes and resolves the associations before taking into account associated keys manually passed in the overrides field. This lands up creating undesired entries in the DB as you'd expect it to just link to the provided foreign key, but instead it lands up linking the provided key **and** creating an loose hanging entry in the table as well.

I feel the desired behaviour would be to merge the default attributes and overrides and only afterwards resolve the associations. We noticed this because we have unique constraints on some of our tables and tests were failing because sometimes the factory would happen to create a new entry with the same unique fields and the suite would error out.

Happy to try make a PR for the desired change if this project is still being maintained!

**Comment by thiagomini** [comment]
Hello @dkpoult , thanks for the enthusiasm and for reporting the bug :)

PRs are more than welcome, for sure! I haven't had much time lately to work on it due to my full-time job, but I certainly want to improve it further :)

**Comment by dkpoult** [comment]
@thiagomini we're using Sequelize+Sequelize-Typescript with a Postgres database.

I've created PR #36 to address the issue with a new test case for it, hope it's satisfactory! :)

**Comment by thiagomini** [comment]
Hey @dkpoult , thanks for the contribution, I'll review it as soon as possible and merge if everything looks good!

**Comment by dkpoult** [comment]
Super, thank you 🥳 glad I could help
