### ISSUE TITLE
Sequence feature

### ISSUE THREAD

**Issue by thonythony** [thiagomini/factory-girl-ts#4]
Hello,

I would like to migrate from `factory-girl` to `factory-girl-ts`, but the feature of sequence is missing. It can be very useful when generating data in tests like this : 

```javascript
factory.define('User', User, {
  email: factory.sequence('User.email', n => `dummy-user-${n}@my-domain.com`),
  password: 'some-password'
});
```

On the above example, it ensures that each `n` will be unique. 

Do you planned to implement it ? Or PR will be welcomed ?

**Comment by thiagomini** [comment]
Hey, @thonythony, thank you for your interest in the library! I do have plans to add it, but I've been really busy the last few weeks. A PR is more than welcome!
